use crate::contract::CheckStatus;
use crate::sandbox::{self, CommandPolicy, SandboxConfig};
use crate::verification::helpers::truncate;
use crate::verification::RawResult;
use regex::Regex;
use tokio::process::Command;
use tracing::{debug, info};

/// Execute a command with security-aware dispatch.
///
/// - `sandbox_override`: If `Some(true)`, force execution in a container.
///   If `Some(false)` or `None`, subject to whitelist validation.
/// - `internal`: If `true`, the command was generated by the server itself
///   (e.g., for Python checks) and bypasses dangerous-pattern checks.
pub(crate) async fn execute_command(
    command: &str,
    working_dir: Option<&str>,
    timeout_secs: u64,
    sandbox_override: Option<bool>,
    internal: bool,
) -> Result<(i32, String, String), String> {
    // If sandbox is explicitly requested, always use container
    if sandbox_override == Some(true) {
        info!(command = %command, "Sandbox explicitly requested — executing in container");
        let config = SandboxConfig::from_env();
        return sandbox::execute_sandboxed(command, working_dir, timeout_secs, &config).await;
    }

    // Validate the command through the security policy
    let policy = sandbox::validate_command(command, internal);
    debug!(command = %command, ?policy, "Command policy evaluation");

    match policy {
        CommandPolicy::Allow => {
            // Run directly on host (original behavior)
            execute_on_host(command, working_dir, timeout_secs).await
        }
        CommandPolicy::Sandbox => {
            // Unknown command — run in container
            let config = SandboxConfig::from_env();
            sandbox::execute_sandboxed(command, working_dir, timeout_secs, &config).await
        }
        CommandPolicy::Deny(reason) => Err(format!("🛡 SECURITY: {reason}")),
    }
}

/// Execute a command directly on the host (no sandboxing).
pub(crate) async fn execute_on_host(
    command: &str,
    working_dir: Option<&str>,
    timeout_secs: u64,
) -> Result<(i32, String, String), String> {
    let mut cmd = Command::new("sh");
    cmd.arg("-c").arg(command);

    if let Some(dir) = working_dir {
        cmd.current_dir(dir);
    }

    let output = tokio::time::timeout(std::time::Duration::from_secs(timeout_secs), cmd.output())
        .await
        .map_err(|_| format!("Command timed out after {timeout_secs}s"))?
        .map_err(|e| format!("Failed to execute command: {e}"))?;

    let code = output.status.code().unwrap_or(-1);
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    Ok((code, stdout, stderr))
}

pub(crate) async fn run_command_succeeds(
    command: &str,
    working_dir: Option<&str>,
    timeout_secs: u64,
    sandbox_override: Option<bool>,
) -> RawResult {
    match execute_command(command, working_dir, timeout_secs, sandbox_override, false).await {
        Ok((code, stdout, stderr)) => {
            let passed = code == 0;
            let combined = format!("stdout:\n{stdout}\nstderr:\n{stderr}");
            RawResult {
                status: if passed {
                    CheckStatus::Passed
                } else {
                    CheckStatus::Failed
                },
                message: if passed {
                    "Command succeeded (exit code 0)".to_string()
                } else {
                    format!("Command failed with exit code {code}")
                },
                details: Some(truncate(&combined, 2000)),
            }
        }
        Err(e) => RawResult {
            status: CheckStatus::Failed,
            message: format!("Command execution error: {e}"),
            details: None,
        },
    }
}

pub(crate) async fn run_command_output_matches(
    command: &str,
    pattern: &str,
    working_dir: Option<&str>,
    timeout_secs: u64,
    sandbox_override: Option<bool>,
) -> RawResult {
    let re = match Regex::new(pattern) {
        Ok(r) => r,
        Err(e) => {
            return RawResult {
                status: CheckStatus::Failed,
                message: format!("Invalid regex pattern: {e}"),
                details: None,
            }
        }
    };

    match execute_command(command, working_dir, timeout_secs, sandbox_override, false).await {
        Ok((code, stdout, stderr)) => {
            let matches = re.is_match(&stdout);
            let combined = format!("stdout:\n{stdout}\nstderr:\n{stderr}");
            RawResult {
                status: if code == 0 && matches {
                    CheckStatus::Passed
                } else {
                    CheckStatus::Failed
                },
                message: if code != 0 {
                    format!("Command failed with exit code {code}")
                } else if matches {
                    format!("Output matches pattern '{pattern}'")
                } else {
                    format!("Output does NOT match pattern '{pattern}'")
                },
                details: Some(truncate(&combined, 2000)),
            }
        }
        Err(e) => RawResult {
            status: CheckStatus::Failed,
            message: format!("Command execution error: {e}"),
            details: None,
        },
    }
}
